"""Omega AI v3.7.0 — PDF Report Generator
Generate styled PDF reports from data. Uses HTML-to-PDF approach.
"""
from __future__ import annotations

import time
from pathlib import Path
from typing import Any


class PDFGenerator:
    """Generate PDF reports from structured data."""

    HTML_TEMPLATE = """<!DOCTYPE html>
<html><head><meta charset="utf-8">
<style>
body{{font-family:'Segoe UI',Arial,sans-serif;margin:40px;color:#333;line-height:1.6}}
h1{{color:#00e5ff;border-bottom:3px solid #00e5ff;padding-bottom:10px}}
h2{{color:#555;border-bottom:1px solid #ddd;padding-bottom:5px;margin-top:30px}}
table{{width:100%;border-collapse:collapse;margin:15px 0}}
th{{background:#00e5ff;color:#fff;padding:10px;text-align:left}}
td{{padding:8px;border-bottom:1px solid #eee}}
.footer{{margin-top:40px;padding-top:20px;border-top:1px solid #ddd;color:#999;font-size:12px;text-align:center}}
.metric{{display:inline-block;margin:10px 20px 10px 0;padding:15px;background:#f8f9fa;border-radius:8px}}
.metric-value{{font-size:28px;font-weight:bold;color:#00e5ff}}
.metric-label{{font-size:12px;color:#666;text-transform:uppercase}}
</style></head><body>
<h1>{title}</h1>
<p style="color:#666">Generated by Luqi-AI v3.7.0 on {date}</p>
{content}
<div class="footer">Luqi-AI v3.7.0 &bull; Intelligent Assistant &bull; {date}</div>
</body></html>"""

    def __init__(self, output_dir: str = "reports") -> None:
        self._output_dir = Path(output_dir)
        self._output_dir.mkdir(exist_ok=True)

    def generate_report(self, title: str, sections: list[dict[str, Any]], file_name: str | None = None) -> dict[str, Any]:
        """Generate a PDF report from sections."""
        try:
            import weasyprint
            has_weasyprint = True
        except ImportError:
            has_weasyprint = False

        content_html = ""
        for section in sections:
            stype = section.get("type", "text")
            if stype == "metrics":
                content_html += '<div style="margin:20px 0">'
                for m in section.get("data", []):
                    content_html += f'<div class="metric"><div class="metric-value">{m["value"]}</div><div class="metric-label">{m["label"]}</div></div>'
                content_html += '</div>'
            elif stype == "table":
                content_html += f'<h2>{section.get("title", "")}</h2><table>'
                headers = section.get("headers", [])
                content_html += '<tr>' + ''.join(f'<th>{h}</th>' for h in headers) + '</tr>'
                for row in section.get("rows", []):
                    content_html += '<tr>' + ''.join(f'<td>{c}</td>' for c in row) + '</tr>'
                content_html += '</table>'
            elif stype == "text":
                content_html += f'<h2>{section.get("title", "")}</h2><p>{section.get("content", "")}</p>'
            elif stype == "list":
                content_html += f'<h2>{section.get("title", "")}</h2><ul>'
                for item in section.get("items", []):
                    content_html += f'<li>{item}</li>'
                content_html += '</ul>'

        date_str = time.strftime("%Y-%m-%d %H:%M:%S")
        html = self.HTML_TEMPLATE.format(title=title, date=date_str, content=content_html)
        output_file = file_name or f"report_{int(time.time())}.pdf"
        output_path = self._output_dir / output_file

        if has_weasyprint:
            weasyprint.HTML(string=html).write_pdf(str(output_path))
        else:
            # Fallback: save as HTML, user can print to PDF
            html_path = output_path.with_suffix(".html")
            html_path.write_text(html)
            return {
                "success": True,
                "file": str(html_path),
                "note": "weasyprint not installed. Saved as HTML — open in browser and print to PDF. Install: pip install weasyprint",
            }

        return {"success": True, "file": str(output_path), "pages": len(sections)}

    def generate_system_report(self) -> dict[str, Any]:
        """Generate a full system status report as PDF."""
        from config import CONFIG
        sections = [
            {"type": "metrics", "data": [
                {"value": CONFIG["VERSION"], "label": "Version"},
                {"value": "49", "label": "Modules"},
                {"value": "35", "label": "API Endpoints"},
                {"value": "132", "label": "Tests"},
            ]},
            {"type": "text", "title": "System Overview", "content": "Luqi-AI is a fully-featured intelligent assistant with 49 capability modules, 35 API endpoints, 132 tests, and 5-platform support."},
            {"type": "list", "title": "Capabilities", "items": [
                "Research & Deep Analysis", "Investment & Mining", "Tax Calculation (12 countries)",
                "Translation (59 languages)", "Wisdom Engine (165+ quotes)", "Digital Transformation",
                "File Analysis (PDF/DOCX/XLSX)", "Data Visualization", "Workflow Automation",
                "Voice Interface", "Knowledge Base", "Plugin Marketplace",
            ]},
        ]
        return self.generate_report("Luqi-AI System Report", sections, f"system_report_{int(time.time())}.pdf")
