"""
pdf_generator.py - PDF report generation for LUQI AI.

Attempts to use ``fpdf2`` (``from fpdf import FPDF``) for real PDF generation.
If fpdf2 is unavailable it gracefully falls back to generating HTML, base-64
encoding it, and returning a message instructing the consumer to render the
HTML or install the dependency.

Usage::

    engine = __import__("pdf_generator").PDFGenerator()
    result = engine.generate("# Hello\\n\\nThis is a report.", title="My Report")
    result = engine.generate_from_data({"revenue": 1_000_000}, title="Tax Report")
"""

from __future__ import annotations

import base64
import logging
from io import BytesIO
from typing import Dict, Any, Optional

logger = logging.getLogger(__name__)

# ---------------------------------------------------------------------------
# Optional dependency: fpdf2
# ---------------------------------------------------------------------------
try:
    from fpdf import FPDF
    _HAS_FPDF = True
except ImportError:  # pragma: no cover
    FPDF = None
    _HAS_FPDF = False
    logger.warning(
        "fpdf2 is not installed. PDF generation will fall back to HTML. "
        "Install it: pip install fpdf2"
    )


class PDFGenerator:
    """PDF report generator with fpdf2 + HTML fallback."""

    # --------------------------------------------------------------------- #
    # Internal helpers
    # --------------------------------------------------------------------- #
    @staticmethod
    def _html_escape(text: str) -> str:
        """Escape HTML special characters."""
        return (
            text.replace("&", "&amp;")
            .replace("<", "&lt;")
            .replace(">", "&gt;")
            .replace('"', "&quot;")
        )

    def _content_to_html(self, content: str, title: str) -> str:
        """Convert plain-text / markdown-ish content to simple HTML."""
        lines = content.splitlines()
        body_parts: list[str] = []
        in_list = False

        for line in lines:
            stripped = line.strip()
            if stripped.startswith("# "):
                if in_list:
                    body_parts.append("</ul>")
                    in_list = False
                body_parts.append(f"<h1>{self._html_escape(stripped[2:])}</h1>")
            elif stripped.startswith("## "):
                if in_list:
                    body_parts.append("</ul>")
                    in_list = False
                body_parts.append(f"<h2>{self._html_escape(stripped[3:])}</h2>")
            elif stripped.startswith("### "):
                if in_list:
                    body_parts.append("</ul>")
                    in_list = False
                body_parts.append(f"<h3>{self._html_escape(stripped[4:])}</h3>")
            elif stripped.startswith("- ") or stripped.startswith("* "):
                if not in_list:
                    body_parts.append("<ul>")
                    in_list = True
                body_parts.append(f"<li>{self._html_escape(stripped[2:])}</li>")
            elif stripped == "---":
                if in_list:
                    body_parts.append("</ul>")
                    in_list = False
                body_parts.append("<hr/>")
            elif stripped == "":
                if in_list:
                    body_parts.append("</ul>")
                    in_list = False
                body_parts.append("<br/>")
            else:
                if in_list:
                    body_parts.append("</ul>")
                    in_list = False
                body_parts.append(f"<p>{self._html_escape(stripped)}</p>")

        if in_list:
            body_parts.append("</ul>")

        body_html = "\n".join(body_parts)

        return f"""<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{self._html_escape(title)}</title>
    <style>
        body {{ font-family: Arial, sans-serif; margin: 40px; line-height: 1.6; }}
        h1 {{ color: #2c3e50; border-bottom: 2px solid #3498db; padding-bottom: 8px; }}
        h2 {{ color: #34495e; margin-top: 24px; }}
        h3 {{ color: #555; }}
        p  {{ margin: 8px 0; }}
        ul {{ margin: 8px 0; padding-left: 24px; }}
        li {{ margin: 4px 0; }}
        hr {{ border: none; border-top: 1px solid #ddd; margin: 20px 0; }}
        .meta {{ color: #888; font-size: 0.9em; margin-top: 30px; }}
    </style>
</head>
<body>
    <h1>{self._html_escape(title)}</h1>
    {body_html}
    <p class="meta">Generated by LUQI AI PDFGenerator</p>
</body>
</html>"""

    def _data_to_html(self, data: Dict[str, Any], title: str) -> str:
        """Convert a structured dict into an HTML report."""
        rows: list[str] = []
        for key, value in data.items():
            key_str = str(key).replace("_", " ").title()
            if isinstance(value, dict):
                rows.append(f"<h3>{self._html_escape(key_str)}</h3>")
                rows.append("<ul>")
                for sub_k, sub_v in value.items():
                    sub_k_str = str(sub_k).replace("_", " ").title()
                    rows.append(
                        f"<li><strong>{self._html_escape(sub_k_str)}:</strong> "
                        f"{self._html_escape(str(sub_v))}</li>"
                    )
                rows.append("</ul>")
            elif isinstance(value, list):
                rows.append(f"<h3>{self._html_escape(key_str)}</h3>")
                rows.append("<ul>")
                for item in value:
                    rows.append(f"<li>{self._html_escape(str(item))}</li>")
                rows.append("</ul>")
            else:
                rows.append(
                    f"<p><strong>{self._html_escape(key_str)}:</strong> "
                    f"{self._html_escape(str(value))}</p>"
                )

        body_html = "\n".join(rows)

        return f"""<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{self._html_escape(title)}</title>
    <style>
        body {{ font-family: Arial, sans-serif; margin: 40px; line-height: 1.6; }}
        h1 {{ color: #2c3e50; border-bottom: 2px solid #3498db; padding-bottom: 8px; }}
        h2 {{ color: #34495e; margin-top: 24px; }}
        h3 {{ color: #555; margin-top: 18px; }}
        p  {{ margin: 8px 0; }}
        ul {{ margin: 8px 0; padding-left: 24px; }}
        li {{ margin: 4px 0; }}
        .meta {{ color: #888; font-size: 0.9em; margin-top: 30px; }}
    </style>
</head>
<body>
    <h1>{self._html_escape(title)}</h1>
    {body_html}
    <p class="meta">Generated by LUQI AI PDFGenerator</p>
</body>
</html>"""

    def _build_pdf_with_fpdf(self, content_lines: list[str], title: str) -> bytes:
        """Build a PDF using fpdf2."""
        pdf = FPDF()
        pdf.set_auto_page_break(auto=True, margin=15)
        pdf.add_page()

        # Title
        pdf.set_font("Helvetica", "B", 16)
        pdf.cell(0, 10, title, ln=True)
        pdf.ln(4)

        # Body
        pdf.set_font("Helvetica", "", 11)
        for line in content_lines:
            stripped = line.strip()
            if stripped.startswith("# "):
                pdf.set_font("Helvetica", "B", 14)
                pdf.ln(4)
                pdf.cell(0, 8, stripped[2:], ln=True)
                pdf.set_font("Helvetica", "", 11)
            elif stripped.startswith("## "):
                pdf.set_font("Helvetica", "B", 12)
                pdf.ln(3)
                pdf.cell(0, 7, stripped[3:], ln=True)
                pdf.set_font("Helvetica", "", 11)
            elif stripped.startswith("### "):
                pdf.set_font("Helvetica", "B", 11)
                pdf.cell(0, 6, stripped[4:], ln=True)
                pdf.set_font("Helvetica", "", 11)
            elif stripped.startswith("- ") or stripped.startswith("* "):
                pdf.cell(5, 6, "", ln=0)  # indent
                pdf.cell(5, 6, chr(149), ln=0)  # bullet
                pdf.cell(0, 6, stripped[2:], ln=True)
            elif stripped == "":
                pdf.ln(2)
            else:
                pdf.multi_cell(0, 6, stripped)

        result = pdf.output(dest="S")
        if isinstance(result, str):
            result = result.encode("latin-1")
        return result

    def _fallback_to_html(self, html: str, title: str) -> Dict[str, Any]:
        """Return base-64 encoded HTML as the fallback 'PDF'."""
        b64 = base64.b64encode(html.encode("utf-8")).decode("ascii")
        return {
            "result": b64,
            "data": {
                "pdf_base64": b64,
                "title": title,
                "pages": 1,
                "success": True,
                "fallback": True,
                "format": "html",
            },
            "status": "success",
            "success": True,
            "message": (
                "fpdf2 not installed; returned base64-encoded HTML. "
                "Install fpdf2 for real PDF generation: pip install fpdf2"
            ),
        }

    # --------------------------------------------------------------------- #
    # Public API
    # --------------------------------------------------------------------- #
    def generate(self, content: str, title: str = "Report") -> Dict[str, Any]:
        """Generate a PDF (or HTML fallback) from text *content*.

        Parameters
        ----------
        content : str
            Plain-text or markdown-ish content.
        title : str
            Report title.

        Returns
        -------
        dict
            Standard result dictionary with ``pdf_base64``, ``title``,
            ``pages``, and ``success`` keys inside ``data``.
        """
        try:
            if _HAS_FPDF:
                pdf_bytes = self._build_pdf_with_fpdf(
                    content.splitlines(), title
                )
                b64 = base64.b64encode(pdf_bytes).decode("ascii")
                return {
                    "result": b64,
                    "data": {
                        "pdf_base64": b64,
                        "title": title,
                        "pages": 1,
                        "success": True,
                        "fallback": False,
                        "format": "pdf",
                    },
                    "status": "success",
                    "success": True,
                    "message": "",
                }
            else:
                html = self._content_to_html(content, title)
                return self._fallback_to_html(html, title)
        except Exception as exc:  # pragma: no cover
            logger.exception("PDF generation failed")
            return {
                "result": "",
                "data": {
                    "pdf_base64": "",
                    "title": title,
                    "pages": 0,
                    "success": False,
                    "fallback": True,
                    "format": "none",
                },
                "status": "error",
                "success": False,
                "message": str(exc),
            }

    def generate_from_data(
        self, data: Dict[str, Any], title: str = "Report"
    ) -> Dict[str, Any]:
        """Generate a PDF (or HTML fallback) from structured *data*.

        Parameters
        ----------
        data : dict
            Structured data dictionary (e.g. tax report, study plan).
        title : str
            Report title.

        Returns
        -------
        dict
            Same format as :meth:`generate`.
        """
        try:
            if _HAS_FPDF:
                # Convert dict to readable lines
                lines: list[str] = []
                for key, value in data.items():
                    key_str = str(key).replace("_", " ").title()
                    if isinstance(value, dict):
                        lines.append(f"## {key_str}")
                        for sub_k, sub_v in value.items():
                            sub_k_str = str(sub_k).replace("_", " ").title()
                            lines.append(f"- {sub_k_str}: {sub_v}")
                        lines.append("")
                    elif isinstance(value, list):
                        lines.append(f"## {key_str}")
                        for item in value:
                            lines.append(f"- {item}")
                        lines.append("")
                    else:
                        lines.append(f"- {key_str}: {value}")

                pdf_bytes = self._build_pdf_with_fpdf(lines, title)
                b64 = base64.b64encode(pdf_bytes).decode("ascii")
                return {
                    "result": b64,
                    "data": {
                        "pdf_base64": b64,
                        "title": title,
                        "pages": 1,
                        "success": True,
                        "fallback": False,
                        "format": "pdf",
                    },
                    "status": "success",
                    "success": True,
                    "message": "",
                }
            else:
                html = self._data_to_html(data, title)
                return self._fallback_to_html(html, title)
        except Exception as exc:  # pragma: no cover
            logger.exception("PDF generation from data failed")
            return {
                "result": "",
                "data": {
                    "pdf_base64": "",
                    "title": title,
                    "pages": 0,
                    "success": False,
                    "fallback": True,
                    "format": "none",
                },
                "status": "error",
                "success": False,
                "message": str(exc),
            }
